### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by contadordeestorias** [PcBoy111/PCBOT#3]
Hello, 
After having followed all the steps, when launching the bot with the command python bot.py I have the following message : 
Traceback (most recent call last):
  File "bot.py", line 20, in <module>
    from pcbot import utils, config
  File "C:\PCBOT\pcbot\__init__.py", line 10, in <module>
    from .cleverbot import Cleverbot
  File "C:\PCBOT\pcbot\cleverbot.py", line 13, in <module>
    from requests.compat import urlencode
ModuleNotFoundError: No module named 'requests'
How can I solve it please?

**Comment by pckv** [comment]
Hi, this means you don't have the requests library installed. I recommend installing all pcbot specific modules using `python -m pip install discord.py requests future Pillow pendulum==1.0.2 imageio youtube_dl` for the complete package. Also don't forget to setup ffmpeg if you want to use the music features (there's a link to the music plugins which includes a tutorial in the Readme file).

Also noted that the file giving you the error is outdated and should be removed. I'll do this now.

Consider sending me a direct message on discord (PC#0326) for further help, as this bot is very poor on documentation when it comes to usage (it's more just my private bot than anything). I'll answer any question you have on there :ok_hand:

**Comment by contadordeestorias** [comment]
Thank you for your quick answer. I am thinking translating the pokedex into french. If you're interested into it I might give to you the info in french.
