### ISSUE TITLE
Problem when launching the bot

### ISSUE THREAD

**Issue by contadordeestorias** [PcBoy111/PCBOT#4]
Since today (I stopped the bot yesterday) I have this issue when launching the bot :
ERROR 2017-11-03 09:54:22,216 [base_events / asyncio]: Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...op_reading()]>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...op_reading()]>)>
Traceback (most recent call last):
  File "C:\Python\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Python\lib\asyncio\proactor_events.py", line 190, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
asyncio.base_futures.InvalidStateError: Result is not set.
ERROR 2017-11-03 09:54:22,295 [base_events / asyncio]: Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...db\xf6\x1cn.'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...db\xf6\x1cn.'>)>
Traceback (most recent call last):
  File "C:\Python\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Python\lib\asyncio\proactor_events.py", line 188, in _loop_reading
    self._closing)
AssertionError

**Comment by pckv** [comment]
I don't remember the problem here but was solved through discord pm I think
